name: 'dxCompile DNAnexus WDL Workflow'
description: 'dxCompile DNAnexus WDL Workflow to a specified project'
author: 'alexander.bogdanowicz@infinity-biologix.com'
branding:
  icon: 'book'
  color: 'blue'
inputs:
  project-id:
    description: 'The dnanexus project id in which to dxCompile the app'
    required: true
  workflow-directory:
    description: 'The directory in the repo that contains the workflow'
    required: true
    default: '.'
  workflow-name:
    description: 'The name of the wdl in the repo that contains the workflow'
    required: true
    default: 'workflow'
  input-json-name:
    description: 'The name of the input-json file in the repo'
    required: true
    default: 'workflow'
  destination-path:
    description: 'The destination in the project to build the workflow'
    required: true
    default: 'workflow'
  api_token:
    description: 'DNAnexus API token'
    required: true
  apiserver_protocol:
    description: 'DNAnexus API server protocol'
    required: true
    default: 'https'
  apiserver_host:
    description: 'DNAnexus API server hostname'
    required: true
    default: 'api.dnanexus.com'
  apiserver_port:
    description: 'DNAnexus API server port'
    required: true
    default: '443'
outputs:
  project-id:
    description: "The id of the DNAnexus project"
runs:
  using: 'docker'
  image: 'docker://infinitybiologix/dx-compile-wdl:latest'
  args:
    - ${{ inputs.project-id }}
    - ${{ inputs.workflow-directory }}
    - ${{ inputs.workflow-name }}
    - ${{ inputs.input-json-name }}
    - ${{ inputs.destination-path }}
  env:
    DX_SECURITY_CONTEXT: '{"auth_token": "${{ inputs.api_token }}", "auth_token_type": "bearer"}'
    DX_APISERVER_PROTOCOL: ${{ inputs.apiserver_protocol }}
    DX_APISERVER_HOST: ${{ inputs.apiserver_host }}
    DX_APISERVER_PORT: ${{ inputs.apiserver_port }}